@extends('layouts.app')
@section('page-title','Add '.ucfirst(rtrim($type,'s')))
@section('content')
<div class="row"><div class="col-lg-8"><div class="panel"><form method="post" action="{{route('operations.store',['type'=>$type])}}">@csrf
@if($type==='production')<label class="form-label">PRODUCTION DATE</label><input class="form-control mb-3" type="date" name="production_date" value="{{today()->toDateString()}}" required><label class="form-label">QUANTITY PRODUCED (L)</label><input class="form-control mb-3" type="number" step=".01" min=".01" name="quantity" required><label class="form-label">NOTES</label><textarea class="form-control mb-3" name="notes"></textarea>
@elseif($type==='distribution')<label class="form-label">DISTRIBUTION DATE</label><input class="form-control mb-3" type="date" name="distribution_date" value="{{today()->toDateString()}}" required><label class="form-label">QUANTITY DISTRIBUTED (L)</label><input class="form-control mb-3" type="number" step=".01" min=".01" name="quantity" required><label class="form-label">DESTINATION</label><input class="form-control mb-3" name="destination" required><label class="form-label">NOTES</label><textarea class="form-control mb-3" name="notes"></textarea>
@elseif($type==='sales')<label class="form-label">SALE DATE</label><input class="form-control mb-3" type="date" name="sale_date" value="{{today()->toDateString()}}" required><label class="form-label">EXISTING CUSTOMER</label><select class="form-select mb-3" name="customer_id"><option value="">Create a customer below</option>@foreach($customers as $c)<option value="{{$c->customer_id}}">{{$c->name}} · {{$c->phone_number}}</option>@endforeach</select><div class="row"><div class="col"><label class="form-label">NEW CUSTOMER NAME</label><input class="form-control mb-3" name="customer_name"></div><div class="col"><label class="form-label">NEW CUSTOMER PHONE</label><input class="form-control mb-3" name="phone_number"></div></div><div class="row"><div class="col"><label class="form-label">QUANTITY SOLD (L)</label><input class="form-control mb-3" type="number" step=".01" min=".01" name="quantity" required></div><div class="col"><label class="form-label">UNIT PRICE (KSh)</label><input class="form-control mb-3" type="number" step=".01" min="0" name="unit_price" required></div></div>
@else<label class="form-label">CUSTOMER NAME</label><input class="form-control mb-3" name="name" required><label class="form-label">PHONE NUMBER</label><input class="form-control mb-3" name="phone_number" required>@endif
<button class="btn btn-brand">Save record</button><a class="btn btn-light ms-1" href="{{route($type.'.index')}}">Cancel</a></form></div></div></div>
@endsection
